const modal=document.querySelector('#auth-modal'),join=document.querySelector('#join-form'),login=document.querySelector('#login-form'),client=window.NANDAL_API.client;
const esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const show=v=>{join.hidden=v==='login';login.hidden=v!=='login';modal.showModal()};document.querySelectorAll('[data-open-modal]').forEach(b=>b.onclick=()=>show(b.dataset.openModal));document.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>show(b.dataset.switch));document.querySelector('[data-close-modal]').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()};document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelector('#signup-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,n=f.querySelector('.form-message'),v=Object.fromEntries(new FormData(f)),{data,error}=await client.auth.signUp({email:v.email,password:v.password,options:{data:{display_name:v.name,birthdate:v.birthdate}}});n.style.color=error?'#b95443':'#438871';n.textContent=error?error.message:(data.session?'Welcome to NANDAL.':'Check your email to verify your account, then log in.')};
async function enterIfActive(u){const {data:prof}=await client.from('profiles').select('deleted_at').eq('id',u.id).single();if(prof?.deleted_at){await client.auth.signOut();alert('This account has been deleted. Email privacy@nandal.app if this was a mistake.');return}openApp(u)}
document.querySelector('#signin-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,n=f.querySelector('.form-message'),v=Object.fromEntries(new FormData(f)),{data,error}=await client.auth.signInWithPassword({email:v.email,password:v.password});if(error){n.textContent=error.message;document.querySelector('#resend-confirmation').hidden=!/confirm/i.test(error.message);return}modal.close();await enterIfActive(data.user)};
document.querySelector('#resend-confirmation').onclick=async()=>{const f=document.querySelector('#signin-form'),n=f.querySelector('.form-message'),email=f.email.value.trim();if(!email){n.textContent='Enter your email address first.';return}const {error}=await client.auth.resend({type:'signup',email,options:{emailRedirectTo:window.location.origin}});n.style.color=error?'#b95443':'#438871';n.textContent=error?error.message:'A fresh confirmation email has been sent. Open only the newest link.';};
let user,activeMatch=null,messageChannel=null,isModerator=false,reportModal=document.querySelector('#report-modal');
async function photoUrlsFor(ids){if(!ids.length)return{};const {data:photos=[]}=await client.from('photos').select('owner_id,storage_path').in('owner_id',ids).eq('position',0),pathByOwner=Object.fromEntries(photos.map(p=>[p.owner_id,p.storage_path])),urlByOwner={};await Promise.all(ids.map(async id=>{const path=pathByOwner[id];if(!path)return;const {data}=await client.storage.from('profile-photos').createSignedUrl(path,300);if(data)urlByOwner[id]=data.signedUrl}));return urlByOwner}
function photoHtml(id,name,urls){return urls[id]?`<div class="member-photo has-photo"><img src="${urls[id]}" alt=""></div>`:`<div class="member-photo">${esc(name).slice(0,1)}</div>`}
function matchPhotoHtml(id,name,urls){return urls[id]?`<div class="match-photo has-photo"><img src="${urls[id]}" alt=""></div>`:`<div class="match-photo">${esc(name).slice(0,1)}</div>`}
function openReport(id){document.querySelector('#report-target').value=id;document.querySelector('#report-form').reset();document.querySelector('#report-target').value=id;document.querySelector('#report-message').textContent='';reportModal.showModal()}
function showView(name,matchId){document.querySelectorAll('.app-nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));document.querySelectorAll('.app-view').forEach(x=>x.hidden=x.id!==name+'-view');if(name==='messages')loadMessages(matchId);if(name==='safety')loadBlockOptions();if(name==='moderation')loadModeration()}
async function openApp(u){user=u;document.querySelector('.site-header').hidden=true;document.querySelector('main').hidden=true;document.querySelector('footer').hidden=true;document.querySelector('#member-app').hidden=false;document.querySelector('#member-name').textContent=u.user_metadata.display_name||u.email;await Promise.all([loadProfile(),loadDiscover(),loadMatches(),loadPhotos(),loadBlockOptions()])}
async function loadProfile(){const {data}=await client.from('profiles').select('*').eq('id',user.id).single();if(!data)return;isModerator=!!data.is_moderator;const nav=document.querySelector('#nav-moderation');if(nav)nav.hidden=!isModerator;const f=document.querySelector('#profile-form');f.display_name.value=data.display_name||'';f.city.value=data.city||'';f.bio.value=data.bio||'';f.interests.value=(data.interests||[]).join(', ');f.is_discoverable.checked=data.is_discoverable}
async function loadBlockedIds(){const {data:blocks=[]}=await client.from('blocks').select('blocker_id,blocked_id').or(`blocker_id.eq.${user.id},blocked_id.eq.${user.id}`);return new Set(blocks.map(block=>block.blocker_id===user.id?block.blocked_id:block.blocker_id))}
async function loadDiscover(){const [a,b,blocked]=await Promise.all([client.from('profiles').select('id,display_name,bio,city').eq('is_discoverable',true).neq('id',user.id).limit(24),client.from('swipes').select('target_id').eq('actor_id',user.id),loadBlockedIds()]);const seen=new Set((b.data||[]).map(x=>x.target_id)),people=(a.data||[]).filter(p=>!seen.has(p.id)&&!blocked.has(p.id)),urlByOwner=await photoUrlsFor(people.map(p=>p.id)),grid=document.querySelector('#discover-grid');grid.innerHTML=people.map(p=>`<article class="member-card">${photoHtml(p.id,p.display_name,urlByOwner)}<div class="member-card-body"><h3>${esc(p.display_name)}</h3><p>${esc(p.city||'Location not shared')}</p><p>${esc(p.bio||'Still writing their story.')}</p><div class="card-actions"><button data-pass="${p.id}">Pass</button><button class="like" data-like="${p.id}">Like</button><button data-report="${p.id}">•••</button></div></div></article>`).join('');document.querySelector('#discover-empty').hidden=people.length>0;grid.querySelectorAll('[data-pass],[data-like]').forEach(b=>b.onclick=()=>swipe(b.dataset.pass||b.dataset.like,b.dataset.pass?'pass':'like'));grid.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>openReport(b.dataset.report))}
async function swipe(target,choice){try{const r=await window.NANDAL_API.swipe(target,choice);if(r.matched)alert('It’s a match!');await Promise.all([loadDiscover(),loadMatches(),loadBlockOptions()])}catch(e){alert(e.message)}}
async function loadMatches(){const [msResult,blocked]=await Promise.all([client.from('matches').select('*').or(`user_a.eq.${user.id},user_b.eq.${user.id}`),loadBlockedIds()]);const ms=msResult.data||[],visible=ms.filter(m=>!blocked.has(m.user_a===user.id?m.user_b:m.user_a));document.querySelector('#match-count').textContent=visible.length||'';const ids=visible.map(m=>m.user_a===user.id?m.user_b:m.user_a),[{data:ps=[]},urlByOwner]=await Promise.all([ids.length?client.from('profiles').select('id,display_name,city').in('id',ids):{data:[]},photoUrlsFor(ids)]),by=Object.fromEntries(ps.map(p=>[p.id,p]));document.querySelector('#matches-grid').innerHTML=visible.map(m=>{const pid=m.user_a===user.id?m.user_b:m.user_a,p=by[pid]||{};return `<article class="match-card">${matchPhotoHtml(pid,p.display_name||'Match',urlByOwner)}<div class="match-card-body"><h3>${esc(p.display_name||'New match')}</h3><p>${esc(p.city||'')}</p><button class="primary-button" data-message="${m.id}">Say hello</button></div></article>`}).join('');document.querySelector('#matches-empty').hidden=visible.length>0;document.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>showView('messages',b.dataset.message))}
async function loadMessages(openMatchId){const [msResult,blocked]=await Promise.all([client.from('matches').select('*').or(`user_a.eq.${user.id},user_b.eq.${user.id}`),loadBlockedIds()]);const ms=msResult.data||[],visible=ms.filter(m=>!blocked.has(m.user_a===user.id?m.user_b:m.user_a));const ids=visible.map(m=>m.user_a===user.id?m.user_b:m.user_a),{data:ps=[]}=ids.length?await client.from('profiles').select('id,display_name').in('id',ids):{data:[]},by=Object.fromEntries(ps.map(p=>[p.id,p])),matchIds=visible.map(m=>m.id),{data:msgs=[]}=matchIds.length?await client.from('messages').select('match_id,body,created_at').in('match_id',matchIds).order('created_at',{ascending:false}):{data:[]},lastByMatch={};for(const m of msgs)if(!lastByMatch[m.match_id])lastByMatch[m.match_id]=m;const list=document.querySelector('#thread-list'),empty=document.querySelector('#messages-empty'),panel=document.querySelector('#thread-panel');if(!visible.length){list.innerHTML='';panel.hidden=true;empty.hidden=false;activeMatch=null;if(messageChannel){client.removeChannel(messageChannel);messageChannel=null}return}empty.hidden=true;list.innerHTML=visible.map(m=>{const pid=m.user_a===user.id?m.user_b:m.user_a,p=by[pid]||{},last=lastByMatch[m.id];return `<button type="button" class="thread-row" data-match="${m.id}"><strong>${esc(p.display_name||'Match')}</strong><span>${esc(last?.body||'Say hello')}</span></button>`}).join('');list.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>openThread(b.dataset.match));const target=openMatchId||activeMatch;if(target&&visible.some(m=>m.id===target))openThread(target);else{panel.hidden=true;activeMatch=null;if(messageChannel){client.removeChannel(messageChannel);messageChannel=null}}}
async function openThread(matchId){activeMatch=matchId;document.querySelector('#thread-panel').hidden=false;document.querySelectorAll('.thread-row').forEach(b=>b.classList.toggle('active',b.dataset.match===matchId));const {data:m}=await client.from('matches').select('*').eq('id',matchId).single();if(!m)return;const pid=m.user_a===user.id?m.user_b:m.user_a,{data:p}=await client.from('profiles').select('display_name').eq('id',pid).single();document.querySelector('#thread-header').textContent=p?.display_name||'Conversation';await renderThreadMessages(matchId);subscribeMessages(matchId)}
async function renderThreadMessages(matchId){const {data:msgs=[]}=await client.from('messages').select('*').eq('match_id',matchId).order('created_at'),box=document.querySelector('#thread-messages');box.innerHTML=msgs.map(m=>`<div class="chat-bubble ${m.sender_id===user.id?'mine':'theirs'}">${esc(m.body)}</div>`).join('');box.scrollTop=box.scrollHeight}
function subscribeMessages(matchId){if(messageChannel)client.removeChannel(messageChannel);messageChannel=client.channel('messages:'+matchId).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'match_id=eq.'+matchId},()=>{renderThreadMessages(matchId);loadMessages(matchId)}).subscribe()}
async function loadBlockOptions(){if(!user)return;const {data:ms=[]}=await client.from('matches').select('*').or(`user_a.eq.${user.id},user_b.eq.${user.id}`),ids=ms.map(m=>m.user_a===user.id?m.user_b:m.user_a),{data:ps=[]}=ids.length?await client.from('profiles').select('id,display_name').in('id',ids):{data:[]},select=document.querySelector('#block-select');if(!select)return;select.innerHTML='<option value="">Choose someone…</option>'+ps.map(p=>`<option value="${p.id}">${esc(p.display_name)}</option>`).join('')}
async function loadModeration(){if(!isModerator)return;const {data:reports=[]}=await client.from('reports').select('*').order('created_at',{ascending:false}),ids=[...new Set(reports.flatMap(r=>[r.reporter_id,r.reported_id]))],{data:ps=[]}=ids.length?await client.from('profiles').select('id,display_name').in('id',ids):{data:[]},by=Object.fromEntries(ps.map(p=>[p.id,p])),list=document.querySelector('#moderation-list');list.innerHTML=reports.map(r=>`<article class="report-card" data-report="${r.id}" data-reported="${r.reported_id}"><div class="report-head"><span class="report-status status-${r.status}">${esc(r.status)}</span><span class="report-reason">${esc(r.reason.replace('_',' '))}</span></div><p><strong>Reported:</strong> ${esc(by[r.reported_id]?.display_name||'Unknown')}</p><p><strong>Reporter:</strong> ${esc(by[r.reporter_id]?.display_name||'Unknown')}</p>${r.details?`<p class="report-details">${esc(r.details)}</p>`:''}<textarea class="mod-note" placeholder="Moderator note (optional)"></textarea><div class="report-actions"><button type="button" data-mod-status="reviewing">Mark reviewing</button><button type="button" data-mod-status="resolved">Resolve</button><button type="button" data-mod-status="dismissed">Dismiss</button><button type="button" data-mod-hide>Hide profile</button></div></article>`).join('');document.querySelector('#moderation-empty').hidden=reports.length>0;list.querySelectorAll('[data-mod-status]').forEach(b=>b.onclick=()=>modAction(b));list.querySelectorAll('[data-mod-hide]').forEach(b=>b.onclick=()=>modHide(b))}
async function modAction(btn){const card=btn.closest('.report-card'),note=card.querySelector('.mod-note').value.trim();try{await window.NANDAL_API.resolveReport(card.dataset.report,btn.dataset.modStatus,note);await loadModeration()}catch(e){alert(e.message)}}
async function modHide(btn){const card=btn.closest('.report-card'),note=card.querySelector('.mod-note').value.trim();try{await window.NANDAL_API.hideProfile(card.dataset.reported,note);alert('Profile hidden from Discover.')}catch(e){alert(e.message)}}
async function loadPhotos(){const {data=[]}=await client.from('photos').select('*').eq('owner_id',user.id).order('position'),list=document.querySelector('#photo-list');list.innerHTML='';if(!data.length)return;const items=[];for(const p of data){const {data:url}=await client.storage.from('profile-photos').createSignedUrl(p.storage_path,300);items.push({...p,url:url?.signedUrl||''})}list.innerHTML=items.map((p,i)=>`<div class="photo-item" data-id="${p.id}" data-path="${esc(p.storage_path)}"><img class="photo-thumb" src="${p.url}" alt="Your profile photo"><div class="photo-actions"><button type="button" data-move="up"${i?'':' disabled'}>↑</button><button type="button" data-move="down"${i<items.length-1?'':' disabled'}>↓</button><button type="button" data-delete>Remove</button></div></div>`).join('');list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const item=b.closest('.photo-item');try{await window.NANDAL_API.deletePhoto(item.dataset.id,item.dataset.path);await loadPhotos()}catch(e){alert(e.message)}});list.querySelectorAll('[data-move]').forEach(b=>b.onclick=async()=>{const item=b.closest('.photo-item'),rows=[...list.querySelectorAll('.photo-item')],idx=rows.indexOf(item),ids=rows.map(x=>x.dataset.id),dir=b.dataset.move;if(dir==='up'&&idx>0)[ids[idx-1],ids[idx]]=[ids[idx],ids[idx-1]];else if(dir==='down'&&idx<rows.length-1)[ids[idx],ids[idx+1]]=[ids[idx+1],ids[idx]];else return;try{await window.NANDAL_API.reorderPhotos(ids);await loadPhotos()}catch(e){alert(e.message)}})}
document.querySelector('#profile-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,v=new FormData(f),n=document.querySelector('#profile-message'),update={display_name:v.get('display_name').trim(),city:v.get('city').trim()||null,bio:v.get('bio').trim()||null,interests:v.get('interests').split(',').map(x=>x.trim()).filter(Boolean),is_discoverable:v.get('is_discoverable')==='on'},{error}=await client.from('profiles').update(update).eq('id',user.id);n.style.color=error?'#b95443':'#438871';n.textContent=error?error.message:'Profile saved.'};
document.querySelector('#photo-input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const {data=[]}=await client.from('photos').select('id').eq('owner_id',user.id);if(data.length>=6)throw Error('You can add up to six photos.');await window.NANDAL_API.uploadPhoto(f,data.length);await loadPhotos()}catch(e){alert(e.message)}e.target.value=''};
document.querySelector('#compose-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,body=f.body.value.trim();if(!body||!activeMatch)return;try{await window.NANDAL_API.sendMessage(activeMatch,body);f.reset();await renderThreadMessages(activeMatch);await loadMessages(activeMatch)}catch(err){alert(err.message)}};
document.querySelector('#block-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,n=document.querySelector('#block-message'),blocked_id=f.blocked_id.value;if(!blocked_id)return;try{await window.NANDAL_API.block(blocked_id);n.style.color='#438871';n.textContent='Person blocked.';f.reset();await Promise.all([loadDiscover(),loadMatches(),loadBlockOptions(),loadMessages()])}catch(err){n.style.color='#b95443';n.textContent=err.message}};
document.querySelector('[data-close-report]').onclick=()=>reportModal.close();reportModal.onclick=e=>{if(e.target===reportModal)reportModal.close()};
document.querySelector('#report-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,n=document.querySelector('#report-message'),v=Object.fromEntries(new FormData(f));if(!v.reported_id)return;try{await window.NANDAL_API.report(v.reported_id,v.reason,v.details?.trim()||'');n.style.color='#438871';n.textContent='Report sent to moderation.';setTimeout(()=>reportModal.close(),1200)}catch(err){n.style.color='#b95443';n.textContent=err.message}};
document.querySelector('#delete-account').onclick=async()=>{if(!confirm('This permanently removes your photos and clears your profile details. Continue?'))return;const n=document.querySelector('#delete-message');try{const {data:photos=[]}=await client.from('photos').select('id,storage_path').eq('owner_id',user.id);for(const p of photos)await window.NANDAL_API.deletePhoto(p.id,p.storage_path);await window.NANDAL_API.deleteAccount();if(messageChannel)client.removeChannel(messageChannel);await client.auth.signOut();location.reload()}catch(e){n.style.color='#b95443';n.textContent=e.message}};
document.querySelectorAll('.app-nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelector('#sign-out').onclick=async()=>{if(messageChannel)client.removeChannel(messageChannel);await client.auth.signOut();location.reload()};client.auth.getSession().then(({data:{session}})=>{if(session)enterIfActive(session.user)});
